stages:
  - test
  - deploy

before_script:
  - npm install --silent

test:
  image: node:alpine
  stage: test
  services:
    - mongo
  tags:
   - dev
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'test'
  script:
   - npm run test

deploy staging:
  image: docker-dpl
  type: deploy
  tags:
    - dev
  only:
    - dev
  environment:
    name: stageing
    url: https://quienesquienapi.herokuapp.com
  script:
    - dpl --provider=heroku --app=quienesquienapi --api-key=$HEROKU_API_KEY
