stages:
  - test
  - deploy

cache:
  paths:
  - node_modules/

test:
  image: node:alpine
  stage: test
  services:
    - mongo
  tags:
    - docker
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'development'
  script:
    - npm install --silent
    - npm run lint
    - npm run test

deploy staging:
  image: tmaier/dpl
  type: deploy
  tags:
    - heroku
  only:
    - dev
  environment:
    name: stageing
    url: https://quienesquienapi.herokuapp.com
  script:
    - dpl --provider=heroku --app=quienesquienapi --api-key=$HEROKU_API_KEY
