image: node:alpine
stages:
  - lint
  - test
  - deploy

before_script:
  - docker info

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  tags:
   - docker
  script:
   - npm install --silent
   - npm run lint

test:
  stage: test
  services:
    - mongo
  tags:
   - docker
   - mongo
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'test'
  script:
   - npm install --silent
   - npm run test

deploy staging:
  image: tmaier/dpl
  type: deploy
  tags:
    - heroku
  only:
    - dev
  environment:
    name: stageing
    url: https://quienesquienapi.herokuapp.com
  script:
    - dpl --provider=heroku --app=quienesquienapi --api-key=$HEROKU_API_KEY

deploy docker:
  image: docker:latest
  stage: deploy
  tags:
   - docker
  only:
   - dev
  script:
    - docker build -t poder/quienesquienapi:testing .
    - docker login -u $CI_RESGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/quienesquienapi:testing .
