image: node:alpine

services:
  - mongo

stages:
  - test
  - deploy

test:
  stage: test
  tags:
   - dev
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'test'
  script:
   - npm install --silent
   - npm run test

deploy staging:
  type: deploy
  tags:
    - dev
  only:
    - dev
  environment:
    name: stageing
    url: https://quienesquienapi.herokuapp.com
  script:
    - apk add --update git
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/quienesquienapi.git
    - git push -f heroku master

deploy production:
  stage: deploy
  tags:
   - dev
  only:
   - tags
   - master
  environment:
    name: production
    url: https://www.quienesquien.wiki
  script:
   - npm install --silent
   - npm run test
