image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - lint
  - test
  - deploy

before_script:
  - docker build -t poder/quienesquienapi:testing .

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker run --rm poder/quienesquienapi:testing npm run lint

test:
  stage: test
  services:
    - docker:dind
    - mongo
  tags:
    - docker
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'test'
  script:
    - docker run --rm poder/quienesquienapi:testing npm run test

deploy staging:
  image: tmaier/dpl
  type: deploy
  tags:
    - heroku
  only:
    - dev
  environment:
    name: stageing
    url: https://quienesquienapi.herokuapp.com
  script:
    - dpl --provider=heroku --app=quienesquienapi --api-key=$HEROKU_API_KEY

deploy docker:
  stage: deploy
  services:
    - docker:dind
  tags:
   - docker
  only:
   - dev
  script:
    - docker login -u $CI_RESGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/quienesquienapi:testing .
