swagger: "2.0"
host: "localhost:10010"
schemes:
- http
- https
info:
  description: "QuienEsQuien.Wiki API"
  title: "api.quienesquien.wiki"
  version: "1"
  termsOfService: "http://example.com/about/terms"
  contact:
    name: "API Docs"
    url: "https://quienesquien.wiki/contact"
    email: "admin@quienesquien.wiki"
  license:
    name: "Apache 2.0"
    url: "http://example.com"
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /spec.json:
    x-swagger-pipe: swagger_raw
  /persons:
    x-swagger-router-controller: persons
    get:
      description: Returns Array of Person Object to the caller
      operationId: allPersons
      tags:
        - Persons
      parameters:
       - $ref: "#/parameters/_id"
       - $ref: "#/parameters/simple"
       - $ref: "#/parameters/name"
       - $ref: "#/parameters/description"
       - $ref: "#/parameters/text"
       - $ref: "#/parameters/fields"
       - $ref: "#/parameters/sort"
       - $ref: "#/parameters/sortd"
       - $ref: "#/parameters/limit"
       - $ref: "#/parameters/offset"
       - $ref: "#/parameters/gt"
       - $ref: "#/parameters/lt"
       - $ref: "#/parameters/exists"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Person"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /persons/{_id}:
    x-swagger-router-controller: persons
    get:
      description: Returns Person Object
      operationId: singlePerson
      tags:
        - Persons
      parameters:
        - name: _id
          in: path
          description: Internal ID of person
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Person"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /organizations:
    x-swagger-router-controller: organizations
    get:
     tags:
       - Organizations
     description: Returns all organizations
     operationId: allOrganizations
     parameters:
       - name: "limit"
         in: query
         description: Number of returned documents
         type: integer
         default: 50
       - $ref: "#/parameters/_id"
       - $ref: "#/parameters/simple"
       - $ref: "#/parameters/name"
       - $ref: "#/parameters/description"
       - $ref: "#/parameters/text"
       - $ref: "#/parameters/fields"
       - $ref: "#/parameters/sort"
       - $ref: "#/parameters/sortd"
       - $ref: "#/parameters/offset"
       - $ref: "#/parameters/gt"
       - $ref: "#/parameters/lt"
       - $ref: "#/parameters/exists"

     responses:
       200:
         description: An array of organizations
         schema:
           $ref: '#/definitions/Organization'
       default:
         description: Error
         schema:
           $ref: "#/definitions/ErrorResponse"

  /organizations/{_id}:
    x-swagger-router-controller: organizations
    get:
     tags:
       - Organizations
     description: Returns an organizations
     operationId: singleOrganization
     parameters:
       - name: _id
         in: path
         description: Internal ID of organization
         required: true
         type: string
     responses:
       200:
         description: An array of organizations
         schema:
           $ref: '#/definitions/Organization'
       default:
         description: Error
         schema:
           $ref: "#/definitions/ErrorResponse"

  /contracts:
    x-swagger-router-controller: contracts
    get:
      operationId: allContracts
      description: "Returns all contracts"
      tags:
        - Contracts
      summary: "Short Summary of API Method"
      parameters:
        -
          in: "query"
          name: "title"
          description: "Title of contract."
          type: "string"
          required: false
          enum:
            - "Red%20Local"
        -
          in: "query"
          name: "type"
          description: "Contract type"
          type: "string"
          required: false
        -
          in: "query"
          name: "status"
          description: "Contract Status"
          type: "string"
          required: false
        -
          in: "query"
          name: "ocid"
          description: "Open Contracting Identifier"
          type: "string"
          required: false
        -
          in: "query"
          name: "procedure_type"
          description: "Type of contractural proceedure"
          type: "string"
          required: false
        -
          in: "query"
          name: "amount"
          description: "Monetary amount paid to supplier"
          type: "number"
          required: false
        -
          in: "query"
          name: "currency"
          description: "Currency of given amount"
          type: "string"
          required: false
        -
          in: "query"
          name: "provider"
          description: "Provider of given service"
          type: "string"
          required: false
        -
          in: "query"
          name: "department"
          description: "responsible public department"
          type: "string"
          required: false
        -
          in: "query"
          name: "dependency"
          description: "responsible public dependency"
          type: string
          required: false
        - $ref: "#/parameters/start_date"
        - $ref: "#/parameters/end_date"
        - $ref: "#/parameters/text"
        - $ref: "#/parameters/fields"
        - $ref: "#/parameters/sort"
        - $ref: "#/parameters/sortd"
        - $ref: "#/parameters/limit"
        - $ref: "#/parameters/offset"
        - $ref: "#/parameters/gt"
        - $ref: "#/parameters/lt"
        - $ref: "#/parameters/exists"
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/Contract'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /contracts/{_id}:
    x-swagger-router-controller: contracts
    get:
     tags:
       - Contracts
     description: Returns a contract
     operationId: singleContract
     parameters:
       - name: _id
         in: path
         description: Internal ID of contract
         required: true
         type: string
     responses:
       200:
         description: An array of contracts
         schema:
           $ref: '#/definitions/Contract'
       default:
         description: Error
         schema:
           $ref: "#/definitions/ErrorResponse"

definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

  Address:
    properties:
      street:
        type: string
      city:
        type: string
      state:
        type: string
      postal_code:
        type: string
      country:
        type: string
      phones:
        type: string
      emails:
        type: string
      website:
        type: string

  Reference:
    properties:
      name:
        type: string
      url:
        type: string
      author:
        type: string
      publication_date:
        type: string
        format: date-time
      publication_place:
        type: string

  Membership:
    properties:
      person:
        type: string
      person_id:
        type: string
      org:
        type: string
      org_id:
        type: string
      role:
        type: string
      department:
        type: string

  ContractSubDoc:
    properties:
      _id:
        type: "string"
        minLength: 1
      type:
        type: "string"
        minLength: 1
      status:
        type: "string"
        minLength: 1
      title:
        type: "string"
        minLength: 1
      account_admin:
        type: "string"
        minLength: 1
      ocid:
        type: "string"
        minLength: 1
      procedure_type:
        type: "string"
        minLength: 1
      amount:
        type: "number"
      currency:
        type: "string"
        minLength: 1
      suppliers_org:
        type: string
      suppliers_person:
        type: string
      references:
        type: array
        items:
          $ref: '#/definitions/Reference'
      department:
        type: string
        minLength: 1
      clave_uc:
        type: string
        minLength: 1
      start_date:
        type: string
        format: date-time
        minLength: 1
      end_date:
        type: string
        minLength: 1
      character:
        type: string
        minLength: 1
      dependency:
        type: string

  Person:
    properties:
      _id:
        type: string
        minLength: 1
      simple:
        type: string
        minLength: 1
      name:
        type: string
        minLength: 1
      names:
        type: array
        items:
          properties: {}
      first_name:
        type: string
        minLength: 1
      family_name:
        type: string
        minLength: 1
      prefix:
        type: string
        minLength: 1
      suffix:
        type: string
        minLength: 1
      created_at:
        type: string
        minLength: 1
      source:
        type: string
        minLength: 1
      contract_count:
        type: number
      board:
        type: array
        items:
          $ref: '#/definitions/Membership'
      shares:
        type: array
        items:
          $ref: '#/definitions/Membership'
      suppliesContract:
        type: array
        items:
          $ref: '#/definitions/ContractSubDoc'

  PersonSubDoc:
    properties:
      _id:
        type: string
        minLength: 1
      simple:
        type: string
        minLength: 1
      name:
        type: string
        minLength: 1
      names:
        type: array
        items:
          properties: {}
      first_name:
        type: string
        minLength: 1
      family_name:
        type: string
        minLength: 1
      prefix:
        type: string
        minLength: 1
      suffix:
        type: string
        minLength: 1
      created_at:
        type: string
        minLength: 1
      source:
        type: string
        minLength: 1
      contract_count:
        type: number


  Organization:
    properties:
      simple:
        type: string
      name:
        type: string
      category:
        type: string
        enum:
          - public
          - private
          - party
      address:
          $ref: '#/definitions/Address'
      initials:
         type: string
      description:
         type: string
      created_at:
        type: string
        minLength: 1
      source:
        type: string
        minLength: 1
      contract_count:
        type: number

      memberships:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          $ref: '#/definitions/Membership'

      board:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          $ref: '#/definitions/Membership'

      shares:
        type: "array"
        uniqueItems: true
        minItems: 1
        items:
          $ref: '#/definitions/Membership'

      share:
        type: "array"
        uniqueItems: true
        minItems: 1
        items:
          $ref: '#/definitions/Membership'

      contracts:
        type: "array"
        uniqueItems: true
        minItems: 1
        items:
          $ref: '#/definitions/ContractSubDoc'

  OrganizationSubDoc:
    properties:
      simple:
        type: string
      name:
        type: string
      category:
        type: string
        enum:
          - public
          - private
          - party
      address:
          $ref: '#/definitions/Address'
      initials:
         type: string
      description:
         type: string
      created_at:
        type: string
        minLength: 1
      source:
        type: string
        minLength: 1
      contract_count:
        type: number

  Contract:
    description: "A Contract"
    type: "object"
    properties:
      _id:
        type: "string"
        minLength: 1
      type:
        type: "string"
        minLength: 1
      status:
        type: "string"
        minLength: 1
      title:
        type: "string"
        minLength: 1
      account_admin:
        type: "string"
        minLength: 1
      ocid:
        type: "string"
        minLength: 1
      procedure_type:
        type: "string"
        minLength: 1
      amount:
        type: "number"
      currency:
        type: "string"
        minLength: 1
      suppliers_org:
        type: array
        items:
          $ref: '#/definitions/OrganizationSubDoc'
      suppliers_person:
        type: array
        items:
          $ref: '#/definitions/PersonSubDoc'
      references:
        type: array
        items:
          properties: {}
      department:
        type: string
        minLength: 1
      clave_uc:
        type: string
        minLength: 1
      start_date:
        type: string
        format: date-time
        minLength: 1
      end_date:
        type: string
        format: date-time
        minLength: 1
      character:
        type: string
        minLength: 1
      dependency:
        type: string
      # FIXME remove
      country:
        type: string


parameters:
  name:
    name: name
    in: query
    description: The entity's name
    type: string
  _id:
    in: query
    name: _id
    description: Internal ID of entity
    type: string
  simple:
    in: query
    name: simple
    description: Simpified name of person
    type: string
  description:
    in: query
    name: description
    description: Description of entity
    type: string
  fields:
    in: query
    name: fields
    description: fields to return in results
    type: string
  text:
    in: query
    name: text
    description: Perform a text search
    type: boolean
    enum:
      - true
      - false
  exists:
    in: query
    name: exists
    description: Perform a text search
    type: boolean
    enum:
      - true
      - false
  sort:
    in: query
    name: sort
    description: Sort by given field.
    type: string
  sortd:
    in: query
    name: sortd
    description: Sort direction.
    type: string
  limit:
    name: limit
    in: query
    description: Number of returned documents
    type: integer
    default: 100
  offset:
    name: offset
    in: query
    description: Number of returned documents
    type: integer
    default: 0
  start_date:
    in: query
    name: start_date
    description: Beginning Date
    type: string
    format: date-time
    enum:
      - 2014-04-20
  end_date:
    in: query
    name: end_date
    description: End Date
    type: string
    format: date-time

  gt:
    in: "query"
    name: "gt"
    description: Greater than
    type: "string"

  lt:
    in: "query"
    name: "lt"
    description: Less than
    type: "string"
